//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Student = new HashSet<Student>();
            this.SubjectFaculty = new HashSet<SubjectFaculty>();
        }
    
        public int ID_Faculty { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime Creation_date { get; set; }
        public int University { get; set; }
        public int City { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual University University1 { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<SubjectFaculty> SubjectFaculty { get; set; }
    }
}
