//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Birth_date { get; set; }
        public int Semester { get; set; }
        public int Faculty { get; set; }
        public int City { get; set; }
    
        public virtual Faculty Faculty1 { get; set; }
    }
}
