//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectFaculty
    {
        public int ID_SubjectFaculty { get; set; }
        public int subject { get; set; }
        public int faculty { get; set; }
    
        public virtual Faculty Faculty1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
